name: Build and Deploy to AWS Fargate

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-1
  ECR_REPOSITORY: webapp/webapp
  IMAGE_TAG: latest
  IMAGE_NAME: ${{ secrets.ECR_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push image to ECR
        uses: docker/build-push-action@v6
        with:
          context: ./src/WebApp
          file: ./src/WebApp/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}
          platforms: linux/arm64

      - name: Install Copilot CLI
        run: |
          curl -Lo copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux
          chmod +x copilot
          sudo mv copilot /usr/local/bin/copilot
          copilot --version

      - name: Deploy with Copilot
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          COPILOT_APP: ${{ secrets.COPILOT_APP }}
          COPILOT_ENV: ${{ secrets.COPILOT_ENV }}
          COPILOT_SERVICE: ${{ secrets.COPILOT_SERVICE }}
        run: |
          echo "Deploying to Copilot environment..."
          copilot svc deploy --name "${COPILOT_SERVICE}" --env "${COPILOT_ENV}" --app "${COPILOT_APP}" --force

      - name: Deployment complete
        run: echo "Deployment to AWS Fargate complete."

